stages:
  - test

test-rust:
  stage: test
  image: rust:latest
  variables:
    KCOV_DISCARD_CACHE: "false"
    APT_CACHE_DIR: apt-cache
  before_script:
    - mkdir -pv $APT_CACHE_DIR && apt-get -qq update
    - apt-get -qq -o dir::cache::archives="$APT_CACHE_DIR" install -y
      binutils-dev libcurl4-openssl-dev zlib1g-dev libdw-dev libiberty-dev
      cmake
    - ./rust/tools/build-kcov
    - rustc --version
    - cargo --version
    - ./rust/tools/kcov/bin/kcov --version
  script:
    - cd rust && make coverage
  after_script:
    - cat rust/target/coverage/index.json
  coverage: '"covered":"(\d+(?:\.\d+)?)",'
  cache:
    untracked: true
    paths:
      - apt-cache
      - rust/tools/kcov
  only:
    - rust
