stages:
  - vet
  - test

# rust {{{
check-rust:
  stage: vet
  image: registry.gitlab.com/grauwoelfchen/portolan/rust-vet-tools:nightly
  before_script:
    - rustc --version
    - cargo --version
    - cargo fmt --version
  script:
    - cd src/rust && make format
  only:
    refs:
      - branches
      - merge_requests
    changes:
      - README.md
      - CHANGELOG
      - .env.ci.sample
      - .gitignore
      - .gitlab-ci.yml
      - bin/**/*
      - src/rust/**/*

test-rust:
  stage: test
  image: registry.gitlab.com/grauwoelfchen/portolan/rust-vet-tools:nightly
  before_script:
    - rustc --version
    - cargo --version
    - kcov --version
  script:
    - cd src/rust && make coverage
  after_script:
    - cat src/rust/target/coverage/index.json
  coverage: '/"covered":"(\d+(?:\.\d+)?)",/'
  only:
    refs:
      - branches
      - merge_requests
    changes:
      - README.md
      - CHANGELOG
      - .env.ci.sample
      - .gitignore
      - .gitlab-ci.yml
      - bin/**/*
      - src/rust/**/*
# }}}

# rust-xunit {{{
check-rust-xunit:
  stage: vet
  image: registry.gitlab.com/grauwoelfchen/portolan/rust-vet-tools:nightly
  before_script:
    - rustc --version
    - cargo --version
    - cargo fmt --version
  script:
    - cd src/rust-xunit && make format
  only:
    refs:
      - branches
      - merge_requests
    changes:
      - README.md
      - CHANGELOG
      - .env.ci.sample
      - .gitignore
      - .gitlab-ci.yml
      - bin/**/*
      - src/rust-xunit/**/*

test-rust-xunit:
  stage: test
  image: registry.gitlab.com/grauwoelfchen/portolan/rust-vet-tools:nightly
  before_script:
    - rustc --version
    - cargo --version
    - kcov --version
  script:
    - cd src/rust-xunit && make coverage
  after_script:
    - cat src/rust-xunit/target/coverage/index.json
  coverage: '/"covered":"(\d+(?:\.\d+)?)",/'
  only:
    refs:
      - branches
      - merge_requests
    changes:
      - README.md
      - CHANGELOG
      - .env.ci.sample
      - .gitignore
      - .gitlab-ci.yml
      - bin/**/*
      - src/rust-xunit/**/*
# }}}

# csharp {{{
check-csharp:
  stage: vet
  image: mcr.microsoft.com/dotnet/sdk:latest
  variables:
    APT_CACHE_DIR: apt-cache
  before_script:
    - mkdir -pv $APT_CACHE_DIR && apt-get -qq update
    - apt-get -qq -o dir::cache::archives="$APT_CACHE_DIR" install -y
      make
    - dotnet --version
  script:
    - cd src/csharp && make format
  only:
    refs:
      - branches
      - merge_requests
    changes:
      - README.md
      - CHANGELOG
      - .env.ci.sample
      - .gitignore
      - .gitlab-ci.yml
      - bin/**/*
      - src/csharp/**/*

test-csharp:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:latest
  variables:
    APT_CACHE_DIR: apt-cache
  before_script:
    - mkdir -pv $APT_CACHE_DIR && apt-get -qq update
    - apt-get -qq -o dir::cache::archives="$APT_CACHE_DIR" install -y
      make
    - dotnet --version
  script:
    # TODO: coverage
    - cd src/csharp && make test
  only:
    refs:
      - branches
      - merge_requests
    changes:
      - README.md
      - CHANGELOG
      - .env.ci.sample
      - .gitignore
      - .gitlab-ci.yml
      - bin/**/*
      - src/csharp/**/*
# }}}

# go-xunit {{{
check-go-xunit:
  stage: vet
  image: golang:latest
  before_script:
    - go version
  script:
    - cd src/go-xunit/src/gitlab.com/grauwoelfchen/go-xunit && make format
  only:
    refs:
      - branches
      - merge_requests
    changes:
      - README.md
      - CHANGELOG
      - .env.ci.sample
      - .gitignore
      - .gitlab-ci.yml
      - bin/**/*
      - src/go-xunit/**/*

# TODO:
# - create docker image for go (Gentoo Linux)
# - coverage
test-go-xunit:
  stage: test
  image: golang:latest
  variables:
    APT_CACHE_DIR: apt-cache
  before_script:
    - mkdir -pv $APT_CACHE_DIR && apt-get -qq update
    - apt-get -qq -o dir::cache::archives="$APT_CACHE_DIR" install -y
      zip
    - go version
  script:
    - cd src/go-xunit/src/gitlab.com/grauwoelfchen/go-xunit && make test
  cache:
    paths:
      - apt-cache
  only:
    refs:
      - branches
      - merge_requests
    changes:
      - README.md
      - CHANGELOG
      - .env.ci.sample
      - .gitignore
      - .gitlab-ci.yml
      - bin/**/*
      - src/go-xunit/**/*
# }}}
