stages:
  - vet
  - test

check-rust:
  stage: vet
  # image: rust:latest
  image: grauwoelfchen/rust-ci-tools:nightly
  before_script:
    - rustc --version
    - cargo --version
    - cargo fmt --version
  script:
    - cd src/rust && make format
  only:
    refs:
      - branches
      - merge_requests
    changes:
      - README.md
      - CHANGELOG
      - .env.ci.sample
      - .gitignore
      - .gitlab-ci.yml
      - bin/**/*
      - src/rust/**/*

check-rust-xunit:
  stage: vet
  # image: rust:latest
  image: grauwoelfchen/rust-ci-tools:nightly
  before_script:
    - rustc --version
    - cargo --version
    - cargo fmt --version
  script:
    - cd src/rust-xunit && make format
  only:
    refs:
      - branches
      - merge_requests
    changes:
      - README.md
      - CHANGELOG
      - .env.ci.sample
      - .gitignore
      - .gitlab-ci.yml
      - bin/**/*
      - src/rust-xunit/**/*

check-csharp:
  stage: vet
  image: mcr.microsoft.com/dotnet/sdk:latest
  variables:
    APT_CACHE_DIR: apt-cache
  before_script:
    - mkdir -pv $APT_CACHE_DIR && apt-get -qq update
    - apt-get -qq -o dir::cache::archives="$APT_CACHE_DIR" install -y
      make
    - dotnet --version
  script:
    - cd src/csharp && make format
  only:
    refs:
      - branches
      - merge_requests
    changes:
      - README.md
      - CHANGELOG
      - .env.ci.sample
      - .gitignore
      - .gitlab-ci.yml
      - bin/**/*
      - src/rust/**/*

check-go-xunit:
  stage: vet
  image: go:latest
  before_script:
    - go version
  script:
    - cd src/go-xunit && make format
  only:
    refs:
      - branches
      - merge_requests
    changes:
      - README.md
      - CHANGELOG
      - .env.ci.sample
      - .gitignore
      - .gitlab-ci.yml
      - bin/**/*
      - src/go-xunit/**/*

test-rust:
  stage: test
  # image: rust:latest
  image: grauwoelfchen/rust-ci-tools:nightly
  before_script:
    - rustc --version
    - cargo --version
    - kcov --version
  script:
    - cd src/rust && make coverage
  after_script:
    - cat src/rust/target/coverage/index.json
  coverage: '/"covered":"(\d+(?:\.\d+)?)",/'
  only:
    refs:
      - branches
      - merge_requests
    changes:
      - README.md
      - CHANGELOG
      - .env.ci.sample
      - .gitignore
      - .gitlab-ci.yml
      - bin/**/*
      - src/rust/**/*

test-rust-xunit:
  stage: test
  # image: rust:latest
  image: grauwoelfchen/rust-ci-tools:nightly
  before_script:
    - rustc --version
    - cargo --version
    - kcov --version
  script:
    - cd src/rust-xunit && make coverage
  after_script:
    - cat src/rust-xunit/target/coverage/index.json
  coverage: '/"covered":"(\d+(?:\.\d+)?)",/'
  only:
    refs:
      - branches
      - merge_requests
    changes:
      - README.md
      - CHANGELOG
      - .env.ci.sample
      - .gitignore
      - .gitlab-ci.yml
      - bin/**/*
      - src/rust-xunit/**/*

test-csharp:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:latest
  variables:
    APT_CACHE_DIR: apt-cache
  before_script:
    - mkdir -pv $APT_CACHE_DIR && apt-get -qq update
    - apt-get -qq -o dir::cache::archives="$APT_CACHE_DIR" install -y
      make
    - dotnet --version
  script:
    # TODO: coverage
    - cd src/csharp && make test
  only:
    refs:
      - branches
      - merge_requests
    changes:
      - README.md
      - CHANGELOG
      - .env.ci.sample
      - .gitignore
      - .gitlab-ci.yml
      - bin/**/*
      - src/rust/**/*

# TODO:
# - create docker image for go (Gentoo Linux)
# - coverage
test-go-xunit:
  stage: test
  image: go:latest
  variables:
    APT_CACHE_DIR: apt-cache
  before_script:
    - mkdir -pv $APT_CACHE_DIR && apt-get -qq update
    - apt-get -qq -o dir::cache::archives="$APT_CACHE_DIR" install -y
      zip
    - go get -u github.com/golang/dep/cmd/dep
    - go version
  script:
    - cd src/go-xunit && make test
  cache:
    paths:
      - apt-cache
  only:
    refs:
      - branches
      - merge_requests
    changes:
      - README.md
      - CHANGELOG
      - .env.ci.sample
      - .gitignore
      - .gitlab-ci.yml
      - bin/**/*
      - src/go-xunit/**/*
