stages:
  - vet
  - test

check-rust:
  stage: vet
  # image: rust:latest
  image: grauwoelfchen/rust-ci-tools:nightly
  before_script:
    - rustc --version
    - cargo --version
    - cargo fmt --version
  script:
    - cd rust && make format
  only:
    - rust

check-rust-unittest:
  stage: vet
  # image: rust:latest
  image: grauwoelfchen/rust-ci-tools:nightly
  before_script:
    - rustc --version
    - cargo --version
    - cargo fmt --version
  script:
    - cd rust-unittest && make format
  only:
    - rust-unittest

check-go-unittest:
  stage: vet
  image: go:latest
  before_script:
    - go version
  script:
    - cd go-unittest && make format
  only:
    - go-unittest

test-rust:
  stage: test
  # image: rust:latest
  image: grauwoelfchen/rust-ci-tools:nightly
  before_script:
    - rustc --version
    - cargo --version
    - kcov --version
  script:
    - cd rust && make coverage
  after_script:
    - cat rust/target/coverage/index.json
  coverage: '/"covered":"(\d+(?:\.\d+)?)",/'
  only:
    - rust

test-rust-unittest:
  stage: test
  # image: rust:latest
  image: grauwoelfchen/rust-ci-tools:nightly
  before_script:
    - rustc --version
    - cargo --version
    - kcov --version
  script:
    - cd rust-unittest && make coverage
  after_script:
    - cat rust-unittest/target/coverage/index.json
  coverage: '/"covered":"(\d+(?:\.\d+)?)",/'
  only:
    - rust-unittest

# TODO:
# - create docker image for go (Gentoo Linux)
# - coverage
test-go-unittest:
  stage: test
  image: go:latest
  variables:
    APT_CACHE_DIR: apt-cache
  before_script:
    - mkdir -pv $APT_CACHE_DIR && apt-get -qq update
    - apt-get -qq -o dir::cache::archives="$APT_CACHE_DIR" install -y
      zip
    - go get -u github.com/golang/dep/cmd/dep
    - go version
  script:
    - cd go-unittest && make test
  cache:
    paths:
      - apt-cache
  only:
    - go-unittest
