# https://github.com/rust-lang-nursery/rustfmt/blob/master/Configurations.md

max_width = 80
tab_spaces = 2

match_block_trailing_comma = true

use_field_init_shorthand = true

reorder_imports = false
reorder_modules = false

# nightly
# indent_style = "Block"
# binop_separator = "Back"

# where_single_line = true
# format_strings = true
# force_multiline_blocks = true

# normalize_comments = true
# wrap_comments = true

# reorder_imported_names = false
# reorder_imports_in_group = false
# reorder_extern_crates = false
# reorder_extern_crates_in_group = false
